#######################
## Lecture 12
#######################

#################
## Section 01
#################

#Logistic regression
# Example - risk of coronary event

#read in data
data <- read.csv('cevent.csv')

#Simple logistic regression
m <- glm(data$event ~ data$chol, family=binomial)
summary(m)

#OR per 1 unit increase
exp(cbind(OR = coef(m), confint.default(m)))

#OR per 1 unit increase and CI of OR
exp(m$coefficients[2])
exp((m$coefficients[2]-qnorm(0.975)*
       summary(m)$coefficients[2,2]))
exp((m$coefficients[2]+qnorm(0.975)*
       summary(m)$coefficients[2,2]))

#OR per 10 unit increase and CI of OR
exp(m$coefficients[2]*10)
exp((m$coefficients[2]-qnorm(0.975)*
       summary(m)$coefficients[2,2])*10)
exp((m$coefficients[2]+qnorm(0.975)*
       summary(m)$coefficients[2,2])*10)

# predicted risk for each patient
(risk <- predict(m, type=c("response")))
# predicted risk for patient with cholesterol of 126
data[48,]
risk[48]

#let's confirm the prob value generated by 
# predict function. 
exp(m$coefficients[1]+m$coefficients[2]*126)/
  (1+exp(m$coefficients[1]+m$coefficients[2]*126))

#################
## Section 02
#################

#multiple logistic regression
data$male <- ifelse(data$sex == "M", 1, 0)
m <- glm(data$event ~ data$chol+data$male+data$age, 
         family=binomial)
summary(m)
# risk of a 60 year old female with cholesterol of 150
exp(-8.53+0.029*150+2.52*0+0.042*60)/
  (1+exp(-8.53+0.029*150+2.52*0+0.042*60))
# risk of a 60 year old male with cholesterol of 150
exp(-8.53+0.029*150+2.52*1+0.042*60)/
  (1+exp(-8.53+0.029*150+2.52*1+0.042*60))

# overall test
#install.packages("aod") # Analysis of Overdispersed Data
library(aod)
wald.test(b=coef(m), Sigma=vcov(m), Terms = 2:4)
# b supplies the coefficients
# Sigma supplies the variance covariance matrix of 
# the error terms, finally Terms tells R which 
# terms in the model are to be tested, in this case, 
# Terms is an integer vector specifying which 
# coefficients should be jointly tested, using a Wald 
# chi-squared or F test

#ORs per 1 unit increase
exp(cbind(OR = coef(m), confint.default(m)))

#################
## Section 03
#################

## Model Fitness in Logistic Regression

m1 <- glm(data$event ~ data$male, family=binomial)
summary(m1)

#ROC curve
#install.packages("pROC")
library(pROC)

data$prob <- predict(m1, type=c("response"))
g <- roc(data$event ~ data$prob)
plot(g)
plot(1-g$specificities, g$sensitivities, type="l", xlab="1-specificity", ylab="Sensitivity", main="ROC curve")
abline(a=0, b=1)
grid()
auc(g)

data$prob <- predict(m, type=c("response"))
g <- roc(data$event ~ data$prob)
plot(g)
plot(1-g$specificities, g$sensitivities, type="l", xlab="1-specificity", ylab="Sensitivity", main="ROC curve")
abline(a=0, b=1)
grid()

#################
## Additional EX
#################

##EX1

## Example to create binary data
clinical.trial <-  data.frame(patient = 1:100, 
                              age = rnorm(100, 
                                          mean = 60, 
                                          sd = 6),
                              treatment = gl(2, 50, 
                                            labels = 
                                              c("Treatment", "Control")),
                              center = sample(paste("Center", LETTERS[1:5]), 
                                              100, replace = TRUE)
                              )

## set some ages to NA (missing)
is.na(clinical.trial$age) <- sample(1:100, 20)

# Discriptive analysis of the data
summary(clinical.trial)

table(clinical.trial$center)

# Create a logical vector indicating whether 
# or not a patient is under 60 or not. 
# We can then pass that into the table function. 
# Also, since there are missing ages, we might be 
# interested 
# in seeing those in the table also. It is shown 
# both ways by setting the useNA argument to table.

## a logical vector is created and passed into table
table(clinical.trial$age < 60)

## the useNA argument shows the missing values, too
table(clinical.trial$age < 60, useNA = "always")

## What about reverse T and F?
table(clinical.trial$age > 60)
table(clinical.trial$age > 60, useNA = "always")


## EX2
#data set mtcars was extracted from the 
#1974 Motor Trend US magazine, and comprises 
#fuel consumption and 
#10 aspects of automobile design and performance 
#for 32 automobiles (1973-74 models).
#In the mtcars data set, the variable vs indicates 
#if a car has a V engine or a straight engine.
#Let us create a model that helps us to predict 
#the probability of a vehicle having a V engine or 
#a straight 
#engine given a weight of 2000 lbs and engine 
#displacement of 180 cubic inches.

data(mtcars)
model <- glm(vs ~ wt + disp, data=mtcars, family=binomial)
newdata = data.frame(wt = 2, disp = 180)
predict(model, newdata, type="response")
