#######################
## Lecture 12
#######################

#################
## Section 01
#################

#Logistic regression
# Example - risk of coronary event

#read in data
data <- read.csv('cevent.csv')
head(data)

#If we fit the data using SLR
m <- lm(event~chol, data=data)
summary(m)
anova(m)
confint(m, level=0.95)

# check model assumptions
par(mfrow = c(2,2))
plot(m, ask=F)
# What do you think?

#Simple logistic regression
## Ensure that your event is coded as 
## 1 = 𝐸𝑣𝑒𝑛𝑡 and 0 = 𝑛𝑜𝑛−𝑒𝑣𝑒𝑛𝑡 
## (numeric, not a factor variable)
## If one of the variables in the model is a factor variable, it is best to create dummy variables (1/0) so that you know exactly what the reference group is
## “family” parameter is a simple way of specifying a choice of variance and link functions When the family is set to binomial, it tells R to perform logistic regression
## http://plantecology.syr.edu/fridley/bio793/glm.html 

m <- glm(data$event ~ data$chol, family=binomial)
## Use the summary() function 
## on the saved regression result 
## to get the regression equation 
## and associated rests for each 
## regression coefficient
summary(m)

## Use the exp() function, which computes 
## the exponential value of a number, 
## on the resulting coefficients to obtain 
## odds ratios for each regression coefficient
#OR per 1 unit increase
exp(cbind(OR = coef(m), confint.default(m)))

#OR per 1 unit increase and CI of OR
exp(m$coefficients[2])
exp((m$coefficients[2]-qnorm(0.975)*
       summary(m)$coefficients[2,2]))
exp((m$coefficients[2]+qnorm(0.975)*
       summary(m)$coefficients[2,2]))

#OR per 10 unit increase and CI of OR
exp(m$coefficients[2]*10)
exp((m$coefficients[2]-qnorm(0.975)*
       summary(m)$coefficients[2,2])*10)
exp((m$coefficients[2]+qnorm(0.975)*
       summary(m)$coefficients[2,2])*10)

## Use the predict() function on the 
## saved regression result to get the 
## predicted risks (probility) 
## for each observation
(risk <- predict(m, type=c("response")))
# predicted risk for patient with 
# cholesterol of 126
data[48,]
risk[48]

#let's confirm the prob value generated by 
# predict function. 
names(m)
m$coefficients
exp(m$coefficients[1]+m$coefficients[2]*126)/
  (1+exp(m$coefficients[1]+m$coefficients[2]*126))

#################
## Section 02
#################

#multiple logistic regression
data$male <- ifelse(data$sex == "M", 1, 0)
m <- glm(data$event ~ data$chol+data$male+data$age, 
         family=binomial)
summary(m)

# overall test
#install.packages("aod") # Analysis of Overdispersed Data
library(aod)
wald.test(b=coef(m), Sigma=vcov(m), Terms = 2:4)
# b supplies the coefficients
# Sigma supplies the variance covariance matrix of 
# the error terms, finally Terms tells R which 
# terms in the model are to be tested, in this case, 
# Terms is an integer vector specifying which 
# coefficients should be jointly tested, using a Wald 
# chi-squared test

#ORs per 1 unit increase
exp(cbind(OR = coef(m), confint.default(m)))

# risk of a 60 year old female with cholesterol of 150
exp(-8.53+0.029*150+2.52*0+0.042*60)/
  (1+exp(-8.53+0.029*150+2.52*0+0.042*60))
# risk of a 60 year old male with cholesterol of 150
exp(-8.53+0.029*150+2.52*1+0.042*60)/
  (1+exp(-8.53+0.029*150+2.52*1+0.042*60))

#################
## Section 03
#################

## Model Fitness in Logistic Regression
m1 <- glm(data$event ~ data$male, family=binomial)
summary(m1)

#ROC curve
#install.packages("pROC")
library(pROC)
# install.packages("caret")
library(caret)

data$prob <- predict(m1, type=c("response"))
head(data, 36)
data$Yhat = ifelse(data$prob > .5, 1, 0)
head(data)
table(data$Yhat, data$event)

# reverse order of 1 and 0
Yhat <- factor(data$Yhat, levels = c("1", "0"))
event <- factor(data$event, levels = c("1", "0"))
# from caret
confusionMatrix(table(Yhat, event))

# ROC curve
par(mfrow = c(1,1))
g <- roc(data$event ~ data$prob)
plot(1-g$specificities, g$sensitivities, 
     type="l", xlab="1-specificity", 
     ylab="Sensitivity", main="ROC curve")
abline(a=0, b=1)
grid()
auc(g) #area under the curve

m <- glm(data$event ~ data$chol+data$male+data$age, 
         family=binomial)
data$prob <- predict(m, type=c("response"))
g <- roc(data$event ~ data$prob)
plot(1-g$specificities, g$sensitivities, type="l", xlab="1-specificity", ylab="Sensitivity", main="ROC curve")
abline(a=0, b=1)
grid()
auc(g) #area under the curve

#################
## Additional EX
#################

##EX1

## Example to create binary data
clinical.trial <-  
  data.frame(patient = 1:100, 
                age = rnorm(100, mean = 60, sd = 6),
                treatment = gl(2, 50, 
                               labels = c("Treatment", "Control")),
                              center = sample(paste("Center", LETTERS[1:5]), 
                                              100, replace = TRUE)
                              )

## set some ages to NA (missing)
is.na(clinical.trial$age) <- sample(1:100, 20)

# Discriptive analysis of the data
summary(clinical.trial)

table(clinical.trial$center)

# Create a logical vector indicating whether 
# or not a patient is under 60 or not. 
# We can then pass that into the table function. 
# Also, since there are missing ages, we might be 
# interested 
# in seeing those in the table also. It is shown 
# both ways by setting the useNA argument to table.

## a logical vector is created and passed into table
table(clinical.trial$age < 60)

## the useNA argument shows the missing values, too
table(clinical.trial$age < 60, useNA = "always")

## What about reverse T and F?
table(clinical.trial$age > 60)
table(clinical.trial$age > 60, useNA = "always")


## EX2
#data set mtcars was extracted from the 
#1974 Motor Trend US magazine, and comprises 
#fuel consumption and 
#10 aspects of automobile design and performance 
#for 32 automobiles (1973-74 models).
#In the mtcars data set, the variable vs indicates 
#if a car has a V engine or a straight engine.
#Let us create a model that helps us to predict 
#the probability of a vehicle having a V engine or 
#a straight 
#engine given a weight of 2000 lbs and engine 
#displacement of 180 cubic inches.

data(mtcars)
model <- glm(vs ~ wt + disp, data=mtcars, family=binomial)
newdata = data.frame(wt = 2, disp = 180)
predict(model, newdata, type="response")
